#!/bin/sh


brewupdate()
{
    echo "Update brew packages"
    brew update
    brew upgrade
    brew cask update
    brew cleanup
    brew cask cleanup

    echo "Remove garbage of sublime text"
    cd "/Users/satouhayabusa/Library/Application Support/Sublime Text 3"
    find . -iregex '.*/__pycache__/.*'
    find . -iregex '.*/__pycache__/.*' | xargs -I{} rm -r {}
    find . -iregex '.*\.pyc'
    find . -iregex '.*\.pyc' | xargs -I{} rm -r {}
    find . -iregex '.*macbook.*'
    find . -iregex '.*macbook.*' | xargs -I{} rm -r {}
    cd -


    cd ~/git/github.com/satoshun/my_setting; git pull origin master; cd -;
}

topcoder()
{
    subpro topcoder
    cd ~/Dropbox/coder; open ContestAppletProd.jnlp ; cd -;
}
