#!/bin/sh


brewupdate()
{
    echo "Update brew packages"
    brew update
    brew upgrade
    brew cask update
    brew cleanup
    brew cask cleanup

    echo "Remove garbage of sublime text"
    cd ~/SkyDrive/preference/Sublime\ Text\ 3/ && sh clear.sh && cd -;

    cd ~/git/github.com/satoshun/my_setting; git pull origin master; cd -;
}

topcoder()
{
    subpro topcoder
    cd ~/Dropbox/coder; open ContestAppletProd.jnlp ; cd -;
}
