update
upgrade


install ack
install autoconf
install automake
install bash-completion
install boot2docker
install git
install gyazo
install go --cross-compile-all
install gradle
install groonga
install imagemagick
install jpeg
install jq
install libmemcached
install libpng
install libtool
install libxml2
install lv
install memcached
install mongodb
install mysql
install nginx
install nkf
install nodebrew
install phantomjs
install pkg-config
install qt
install pyqt5
install python3
install rbenv
install readline
install redis
install ruby-build
install the_silver_searcher
install tig
install tmux
install tree
install mecab
install cairo
install reattach-to-user-namespace
install curl-ca-bundle

# zsh
install z
install zsh
install zsh-completions

# cask
tap phinze/homebrew-cask
install brew-cask

cask install alfred
cask install android-studio
cask install bettertouchtool
cask install dash
cask install dropbox
cask install eclipse-ide
cask install evernote
cask install firefox
cask install genymotion
cask install gimp
cask install google-chrome
cask install hipchat
cask install iterm2
cask install java
cask install keyremap4macbook
cask install sourcetree
cask install vagrant
cask install virtualbox
cask install vlc
cask install xtrafinder
cask install anki
cask install tunnelblick
cask install soundflower
cask install google-japanese-ime
cask install pandoc
cask install bittorrent-sync

# completion
tap homebrew/completions
install vagrant-completion
install pip-completion
install gem-completion

# own library
tap satoshun/commands
install subpro
install subpro-completion
install subpro-zcompletion
install gog
install gitcd

# science
tap homebrew/science
install gcc
cask install mactex
install octave

# sublime
install homebrew/dupes/tidy
tap sanemat/font
install ricty


tap homebrew/dupes
install gdb

# for java
tap caskroom/versions
cask install java7

cask alfred link
link python
linkapps
cleanup
