#!/bin/sh

VAGRANT_PATH=$(cd $(dirname $0);pwd)
CUR_NAME=`pwd`

echo copy file ${CUR_NAME}/Vagrantfile
cp ${VAGRANT_PATH}/Vagrantfile ${CUR_NAME}/

echo copy file ${CUR_NAME}/hosts
cp ${VAGRANT_PATH}/hosts ${CUR_NAME}/

echo ln directory ${CUR_NAME}/provisioning/
ln -s ${VAGRANT_PATH}/provisioning ${CUR_NAME}/provisioning
