#!/bin/sh

VAGRANT_PATH=$(cd $(dirname $0);pwd)
CUR_NAME=`pwd`

echo copy file ${CUR_NAME}/Vagrantfile
cp ${VAGRANT_PATH}/Vagrantfile ${CUR_NAME}/

echo copy directory ${CUR_NAME}/provisioning/
cp -r ${VAGRANT_PATH}/provisioning ${CUR_NAME}/
